### ISSUE TITLE
Upload first BDD

### ISSUE THREAD

**Issue by ogdabou** [GiveMeAShow/givemeashow#31]
Upload des permiers fichiers la BDD de vidéos : 
Futurama / American Dad / Les Griffins / South park

**Comment by ogdabou** [comment]
Tester au préalable la bdd en locale avant de la push sur s3

**Comment by ogdabou** [comment]
American dad episodes seem to run okay.
Futrama ones havnt tany sound, making test tomorrow

**Comment by Ohayu** [comment]
Depends on the video. I tried two of them, once had sound, the other didn't.

**Comment by ogdabou** [comment]
Maybe an encoding problem. Can you just tell me an example of futurama that does have sound and one that doesn't ?

**Comment by ogdabou** [comment]
https://www.digitalocean.com/community/tutorials/initial-server-setup-with-ubuntu-14-04

**Comment by Ohayu** [comment]
Sound : http://d36eb8xsstrlw3.cloudfront.net/Futurama/Films_0/fr/1-Benders_Big_Score.mp4

No sound : http://d36eb8xsstrlw3.cloudfront.net/Futurama/Season_2/fr/20-Anthology_Of_Interest_I.mp4

**Comment by ogdabou** [comment]
nice ty

**Comment by ogdabou** [comment]
Was an encoding issue, need to encode audio in mp3
tested with
http://d36eb8xsstrlw3.cloudfront.net/Futurama/Season_2/fr/20-Anthology_Of_Interest_I.mp4
